name: crypto_quest
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ## Flutter + hoooks
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.4
  ## Flutter only
  # flutter_riverpod: ^2.3.4
  
  shimmer: ^2.0.0
  # auto_route: ^6.3.0
  go_router: ^6.5.7
  hive: ^2.2.3
  drift: ^2.7.0
  dio: ^5.1.1
  connectivity_plus: ^3.0.2

  ### NEW
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 4.0.3
  intl: 0.17.0
  json_path: 0.4.1
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  ## Animation
  rive: ^0.10.4
  lottie: ^2.3.2
  flutter_animate: 4.1.1+1
  page_transition: 2.0.4

  ## TEST library
  ## Dependency Injection / DI and Injectable
  injectable: ^2.1.1
  kiwi: ^4.1.0
  get_it: ^7.3.0
  get: ^4.6.5
  ## other dependencies here
  inject:
    path: ./vendor/inject.dart/package/inject

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.3

  ## TEST library
  inject_generator:
    path: ./vendor/inject.dart/package/inject_generator


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
